---
api-core:
  resource-project-id: zl-win-nodes # Tells that this project hosts the resources created by this api
  shared-vpc-project-id: zl-infra-main
  gce-api-url: https://www.googleapis.com/compute/v1/projects
  gce-timeout-millis: 360000
  gce-zonal-reattempt-errors:
    - ZONE_RESOURCE_POOL_EXHAUSTED
    - QUOTA_EXCEEDED
  gce-reattempt-zones: # make sure we exclude the zone coming in with request from this list.
    - us-central1-c
    - us-west1-b
  grid-defaults:
    machine-type: e2-standard-2
    service-account: zl-runner@zl-win-nodes.iam.gserviceaccount.com
    tags: # these tags are applicable to generated grid for all purposes.
      - runner
      - http-server
    labels: # we should specify only instance specific labels, no labels common with image.
      is-production-instance: true
      zl-runner: true
      locked-by-build: none
      is-deleting: false
    metadata: # specify only metadata that can be given a default.
      time-zone-with-dst: Greenwich Standard Time
    image-specific-labels-key: # Label keys in image those don't belong to a grid.
      - min-stopped-vm
      - min-started-vm
    instance-search-params:
      labels.platform: windows
      labels.is-production-instance: true
      labels.zl-runner: true
      labels.locked-by-build: none
      labels.is-deleting: false
    image-search-params:
      labels.platform: windows
    max-instance-in-search: 10
---
