# TODO: move this file in separate project.
# Before running:
  # cluster should be up and running and known to gcloud/kubectl. Following apps should be installed
  # on cluster:
  # 1. Check if loadBalancerIP is already reserved, if not, do it.
  # 2. ingress-nginx, to deploy first save the intended file from following url
  # https://kubernetes.github.io/ingress-nginx/deploy/, edit it and add loadBalancerIP to the
  # load balancer service that is assigned using --publish-service args. This way we will assign our
  # own static ip
  # 3. cert-manager https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html

# gets into the ingress controller and configures the data
apiVersion: v1
data:
  keep-alive: "600"
  upstream-keepalive-timeout: "600"
kind: ConfigMap
metadata:
  name: nginx-configuration
---
# reference: https://docs.cert-manager.io/en/latest/tutorials/acme/quick-start/index.html
# version from https://github.com/jetstack/cert-manager/releases
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@zylitics.io
    # a secret will be created to store the private key for this ACME account.
    privateKeySecretRef:
      # !!! whenever there is any debugging required, use 'staging' issuers to keep let's encrypt
      # limits from reaching.
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
            # we're telling to create the new ingress-resource under this controller that fulfills
            # the ACME challenge validation requests like putting a file under domain.
            # https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/http01/index.html#ingressclass
---
# https://docs.cert-manager.io/en/latest/tutorials/acme/quick-start/index.html
# version from https://github.com/jetstack/cert-manager/releases
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@zylitics.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zl-k8s-univ-cert
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  secretName: zl-k8s-univ-cert
  # we're giving a list of hosts that will have the same certificate that will be stored in
  # following secret. all hosts here should be pointing to the same load-balancer-ip.
  # add more hosts here, if we send the same hosts more than 5 times on prod env to let's encrypt,
  # you will be blocked for a week, so take care using prod env.
  dnsNames:
    - wzgp.api.zylitics.io
    - wzgp-test.api.zylitics.io
    - front.api.zylitics.io
  issuerRef:
    # when you delete cluster and
    # create a new, cert-manager sends a new certificate req to letsencrypt, if the issuer is prod,
    # this can be done only 5 times a week unless the hostnames in the list are different or its a
    # renewal (happens only when the last issued certificate has reached expiry date otherwise its
    # treated as duplicate which limits to 5). Remember that staging env is just to test whether
    # cert can be issued correctly and isn't a valid CA so you can't use https. While debugging, its
    #  better to access app under http. The limit is imposed per host.
    # https://letsencrypt.org/docs/rate-limits/
    name: letsencrypt-prod
    kind: ClusterIssuer
---